typography_spectrum: 0.19200654095038772
color:
  brandStrength: 0.89832050842233
  lightness: 0.6800224741455168
  saturation: 0.790201967349276
  rhythmicContrast: 0.34253645152784884
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
layout_spectrum: 0.4147542235441506
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9bcbab91-92ac-4b18-abfc-d9ad4275a2f2.png
name: Pets Pets Cash
navigation:
  - name: WDG Public Health
    url: hoverboard.reviews
    type: external
title: Pet Friendly Feeder Reviews
description: Healthy Practices Leading to Healthy Outcomes
